default: &default
 adapter: postgresql
 encoding: unicode
 pool: 10
 username: <%= ENV['COWORX_USER'] %>
 password: <%= ENV['COWORX_PWD'] %>

development:
 <<: *default
 database: <%= ENV['COWORX_DEV_DB'] %>
 host: <%= ENV['COWORX_DEV_HOST'] %>

test:
 <<: *default
 database: <%= ENV['COWORX_TEST_DB'] %>
 host: <%= ENV['COWORX_TEST_HOST'] %>

production:
 <<: *default
 database: <%= ENV['COWORX_PRODUCTION_DB'] %>
 host: <%= ENV['COWORX_PRODUCTION_HOST'] %>
